version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: mydb
      DB_PASS: Tosin-LB
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: Tosin-LB
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb